# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
# production: &production
#   :url: redis://localhost:6379
#   :host: localhost
#   :port: 6379
#   :timeout: 1

production:
  url: redis://localhost:6379/1

development:
  url: redis://localhost:6379/2

test:
  url: redis://localhost:6379/3

local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
